### ISSUE TITLE
Updated schema hashing thoughts

### ISSUE THREAD

**Issue by jamesmunns** [jamesmunns/postcard-rpc#24]
A couple misc thoughts that we might want to do on the next breaking change:

* Use better/larger unique numbers for all the different state fields, instead of sequential small numbers. Potentially pick a bunch of prime u32s instead.
* "mark" endpoint (req, resp) and topic (message) types differently, so even at the same path we can't confuse topics and endpoints, e.g. `hash(path) + hash("Endpoint") + hash(schema(request_type))` or `hash(path) + hash("Topic") + hash(schema(message_type))`
* "mark" endpoint requests and responses separately, e.g. `hash(path) + hash("Endpoint::Request") + hash(schema(request_type))`, to also avoid request/response confusion on the same path

These are all "nice to haves", but might help avoid confusion, particularly when wiring up new transports, or accidental user mis-use. Since these are all at compile time, the minimal added cost is generally not relevant.

**Comment by shanipribadi** [comment]
Is schema evolution a non-goal of this project?
if it's a non-goal, what would be the recommended way of introducing a minor change to the schema,
would it be better to come up with both a new Endpoint (append V2 perhaps) and message version, or can we keep the Endpoint name, while only coming up with new message version?

**Comment by jamesmunns** [comment]
In general for postcard-rpc, the choices I've made means that it's not generally possible to make any changes to a schema: even "minor" changes will affect the hash, and change it.

Note however, this is per-endpoint: It's possible to change only one endpoint, while not changing all others.

The way I've been suggesting people handle this so far:

* Have a version endpoint that never changes the schema, this way you can always make a "get version" call, then the host client can pick which "set" of requests it is allowed to make
* Have the host know the "superset" of all APIs, so it can choose the correct one.

So lets say you have three firmware versions (with fake hashes):

* Firmware Version 1 has these endpoints:
    * `GetVersion` - hash `ABCD`
    * `SetBrightnessV1` - hash `12F4`
    * `GetTemperatureV1` - hash `56DA`
* Firmware Version 2 has these endpoints:
    * `GetVersion` - hash `ABCD`
    * `SetBrightnessV1` - hash `12F4`
    * `GetTemperatureV1` - hash `56DA`
    * `GetHumidityV1` - hash `43B2` (added!)
* Firmware Version 3 has these endpoints:
    * `GetVersion` - hash `ABCD`
    * `SetBrightnessV2` - hash `E465` (changed!)
    * `GetTemperatureV1` - hash `56DA`
    * `GetHumidityV1` - hash `43B2`
    
You could write a HostClient that worked a little like this:

```rust
struct MyClient { ... }

impl MyClient {
    async fn new() -> Self {
        let client = HostClient::new();
        // Get the version at init time
        let version = client.send_resp::<GetVersion>().await?;
        Self { client, version }
    }
    
    async fn get_humidity(&self) -> Result<HumidityV2> {
        match self.version {
            1 => return Err(Unsupported),
            2 => self.client.send_resp::<HumidityV2>().await,
            _ => return Err(BadVersion),
        }
    }
    
    async fn set_brightness(&self, b: Brightness) -> Result<()> {
        match self.version {
            // let's say we can `Into` v2 into v1
            1 => self.client.send_resp::<SetBrightnessV1>(b.into()).await,
            2 => self.client.send_resp::<SetBrightnessV2>(b).await,
            _ => return Err(BadVersion),
        }
    }
    // ...
}
```

**Comment by jamesmunns** [comment]
These have all been applied in the changes between 0.7 and 0.10.
