### ISSUE TITLE
Out-of-band management protocol

### ISSUE THREAD

**Issue by si14** [jamesmunns/postcard-rpc#27]
I'm (well, *will be*) shipping devices and host software to customers. Both the firmware and the host software are being actively developed. Here are two scenarios that worry me a lot:
- Protocol changes. I think avoiding anything complex with forward/backward compatibility in Postcard (RPC) is a good call, but imagine that someone got a new host software version together with a device still flashed with an old firmware. How should they update it? It's a chicken-and-egg problem, since the RPC protocol can't be used to initiate firmware upgrade (the version mismatch will be detected and sensibly cause an error), but for the RPC protocol to be useful again the firmware needs to be updated.
- Bugs. This is a nightmare scenario, but what if I wrote a bugged firmware upgrade RPC handler? This would effectively brick the device, requiring a debug probe to unbrick it. "Just don't write bugs" is fair, but what if Postcard RPC gave me a get-out-of-jail-free card?

In both cases, it'd be really useful to have a simple out-of-band management protocol, the simpler the better. The details are microcontroller-dependent, but at least for RP2040 a single SDK call (reboot to stage 1 bootloader) would be sufficient and really hard to get wrong. It can be completely out-of-band (a separate USB endpoint? using the control endpoint?), or it can just be a magic value in the existing protocol.

There might be more than one layer to this protocol. I can imagine a two-layer protocol, with "reboot into firmware update mode" being the simplest, dumbest, least likely to break layer, and something like "please return the current version/the last panic message/etc" being a bit more complex, but still more reliable than user code.

Either way, I think having something like this in Postcard RPC would be extremely useful. Let me know what you think!

**Comment by jamesmunns** [comment]
I'm going to close this, please feel free to re-open if you'd like to discuss anything in specific.
