### ISSUE TITLE
Raw USB mode is incompatible with having other endpoints

### ISSUE THREAD

**Issue by si14** [jamesmunns/postcard-rpc#29]
Currently, Postcard RPC takes over the entire USB device. However, if it stops doing so, there are several questions:
* how to find the correct USB endpoint and avoid clashes with user endpoints?
* if Postcard RPC can be configured to work on a particular endpoint, should it always be a bulk endpoint? Are there cases for control or isochronous?
There is probably more nuance that I haven't thought about yet.

**Comment by jamesmunns** [comment]
You're correct the current "configure_usb" helper assumes it is the only item, but it is possible to do all configuration manually if you need to. AFAIK the actual Dispatcher and stuff only need access to their input and endpoint channels.

More expressive configuration APIs are welcome, or I'd accept PRs if it's not possible to create the pieces manually like I think. I would like to continue to offer "opinionated and easy" APIs, but not make them mandatory.

Always open to PRs to improve docs.

Re: Control/Isochronous, I don't have any opinions on this. Open to discussing other impls.

**Comment by jamesmunns** [comment]
I'm going to close this, if you have any specific questions please feel free to reopen or open a new issue.
