### ISSUE TITLE
Question, how to send heapless::Vec?

### ISSUE THREAD

**Issue by dvdsk** [jamesmunns/postcard-rpc#48]
As far as I understand all types must implement Schema. Heapless does not provide it so I was surprised to see it mentioned in the discussion of the new *v2 hash* (pr 46). 

Am I missing something here?

**Comment by jamesmunns** [comment]
Hey @dvdsk, I've refactored `postcard` to have the `Schema` trait be part of the new `postcard_schema` crate. New versions of postcard-rpc (v0.8, and I'm about to release v0.9) will rely on this instead, and I've made it easier to implement Schema for any type (and will accept easy PRs that add more impls): https://github.com/jamesmunns/postcard/tree/main/source/postcard-schema/src/impls

**Comment by jamesmunns** [comment]
You're welcome to try these versions out now, but I expect to make another breaking change or two in the near future, and hope that it settles out in a week or two when I launch something based on these new versions.

**Comment by dvdsk** [comment]
Very nice, thanks for letting me now!
