### ISSUE TITLE
Support for MCU Hosts

### ISSUE THREAD

**Issue by cramertj** [jamesmunns/postcard-rpc#50]
The docs currently state that this library is oriented around:
```
//! * A single Client, usually a PC, with access to `std`
//! * A single Server, usually an MCU, without access to `std`
```

Are there plans to or interest in supporting MCU hosts (for MCU<->MCU communication)?

**Comment by jamesmunns** [comment]
Definitely interest, not quite plans yet. Check out https://github.com/jamesmunns/postcard-rpc/issues/37, I'll close this as a dupe, but let me know if that issue doesn't cover it!
